{"name": "Попытка авторизации курьера с неверным паролем возвращает код ответа 404", "status": "passed", "steps": [{"name": "Запрос авторизации курьера", "status": "passed", "parameters": [{"name": "login", "value": "'xnxyposfiv'"}, {"name": "password", "value": "'qwerty12345'"}, {"name": "firstname", "value": "'xeufkxxtmq'"}], "start": 1745013365603, "stop": 1745013365952}], "start": 1745013365245, "stop": 1745013365953, "uuid": "8f47572f-a409-47f2-92ae-68e3c29224e9", "historyId": "80b2129727d09b003d99723a9e6088f1", "testCaseId": "80b2129727d09b003d99723a9e6088f1", "fullName": "test.test_login_courier.TestLoginCourier#test_login_with_invalid_password_return_404", "labels": [{"name": "parentSuite", "value": "test"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "WM-HY9GFP70WW"}, {"name": "thread", "value": "69699-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test.test_login_courier"}]}