{"name": "Попытка авторизации курьера с неверным логином возвращает \"Учетная запись не найдена\"", "status": "passed", "steps": [{"name": "Запрос авторизации курьера", "status": "passed", "parameters": [{"name": "login", "value": "'UserXXX'"}, {"name": "password", "value": "'itoszokhez'"}, {"name": "firstname", "value": "'myzbmmpipn'"}], "start": 1745013366297, "stop": 1745013367053}], "start": 1745013365958, "stop": 1745013367055, "uuid": "5e83e7af-f14f-4015-a576-17ddb90887c3", "historyId": "34e83a934d00b0fd108b8fea137ca6ae", "testCaseId": "34e83a934d00b0fd108b8fea137ca6ae", "fullName": "test.test_login_courier.TestLoginCourier#test_login_with_invalid_login_return_fail", "labels": [{"name": "parentSuite", "value": "test"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "WM-HY9GFP70WW"}, {"name": "thread", "value": "69699-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test.test_login_courier"}]}